# Generated by Django 3.2.6 on 2021-10-31 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nielsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
       
        ),
    
        migrations.AlterField(
            model_name='integrante',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nielsapp.equipo'),
        ),
        migrations.AlterField(
            model_name='integrante',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nielsapp.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
